In [1]:
# ignore warning
import warnings
warnings.filterwarnings("ignore")

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, cross_val_predict
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.dummy import DummyClassifier
from scipy import stats
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from catboost import CatBoostClassifier
# import lightgbm as lgb


import plotly.express as px
import plotly.graph_objects as go

sns.set()

In [20]:

data = pd.read_csv("heart.csv")

give this article a read
https://www.projectpro.io/article/8-feature-engineering-techniques-for-machine-learning/423#toc-4

Discretization(Binning):Grouping based on decision tree sorting (to establish a relationship with target)

Imputation

Categorical Encoding

Feature Splitting

Variable Transformations

Scaling

Creating Features

you can find these is my other files in this file i am working of  outlier capping and discretization

### Handling Outliers

Removal(in other files of this project)

Replacing values

Capping: Capping the maximum and minimum values and replacing them with an arbitrary value or a value from a variable distribution.

Discretization

#### Capping 
is a technique used in feature engineering to handle outliers in a dataset. Outliers are data points that lie far from the majority of the other data points in a dataset, and they can have a significant impact on the analysis and modeling of the data. Capping involves setting a limit or cap on the values of a feature, such that any values that exceed this limit are replaced with the limit value.

For example, if we have a dataset of housing prices, and there are a few extreme values that are much higher than the rest of the values, we can use capping to limit the impact of these outliers on the analysis. We might choose to cap the values of the feature at the 99th percentile, such that any values that exceed this percentile are replaced with the value at the 99th percentile. This can help to make the dataset more robust to outliers and ensure that the analysis is not overly influenced by these extreme values.

Capping can be performed in different ways, such as using a fixed value, a percentile value, or a multiple of the standard deviation. The choice of capping method will depend on the characteristics of the data and the specific requirements of the analysis. It is important to note that capping can have both positive and negative effects on the analysis, and should be used judiciously and with careful consideration of the potential impacts on the results.

## with quantile

In [21]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [22]:
import pandas as pd


cap_value = data['trestbps'].quantile(0.95)  # calculate the 95th percentile value

In [23]:
cap_value

163.19999999999982

In [24]:
#data.loc[data['trestbps'] > cap_value, 'trestbps'] = cap_value  # cap income values above the 95th percentile

In [25]:
def capping(x):
    
    cap_value = data[x].quantile(0.95)  # calculate the 95th percentile value
    print(cap_value)
    data.loc[data[x] > cap_value, x] = cap_value

In [19]:
for i in ["trestbps","chol","thalach","oldpeak"]:
    capping(i)

162.55999999999972
330.0
182.0
3.4

In [26]:
data['trestbps'].quantile(0.95)

163.19999999999982

In [27]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

### with upper and lower quartile

import pandas as pd
import numpy as np

data = pd.read_csv('example.csv')  # load the dataset

q1 = data['Income'].quantile(0.25)  # calculate the 25th percentile
q3 = data['Income'].quantile(0.75)  # calculate the 75th percentile
iqr = q3 - q1  # calculate the interquartile range

lower_cap = q1 - 1.5 * iqr  # calculate the lower cap value
upper_cap = q3 + 1.5 * iqr  # calculate the upper cap value

data.loc[data['Income'] < lower_cap, 'Income'] = lower_cap  # cap income values below the lower threshold
data.loc[data['Income'] > upper_cap, 'Income'] = upper_cap  # cap income values above the upper threshold

### capping with std is in other file of feature engineering